RestaurantMVCClient/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace RestaurantMVCClient.Controllers
{
    public class DishController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }

        // GET all diches
        public ActionResult GetAll()
        {
           
            return View();
        }

        // GET: Ingredient/Add
        public ActionResult Add()
        {
            return View();
        }

        

        public ActionResult AddPrice(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
       
        public ActionResult Find()
        {
            return View();
        }
        
        public ActionResult EditPrice(int priceId, int dishId )
        {
            ViewBag.priceId = priceId;
            ViewBag.dishId = dishId;
            return View();
        }

     
        public ActionResult GetIngredients(int id)
        {
            ViewBag.id = id;
            return View();
            
        }
        public ActionResult AddIngredient(int id)
        {
            ViewBag.id = id;
            return View();
        }

    }
}

RestaurantMVCClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using RestaurantMVCClient.Models;

namespace RestaurantMVCClient.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            
            return View();
        }

        public IActionResult Error()
        {
            return View("/Error");
        }
    }
}

RestaurantMVCClient/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
namespace RestaurantMVCClient.Controllers
{
    public class IngredientController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAll()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        public ActionResult Find()
        {
            return View();
        }
        
    }
}

RestaurantMVCClient/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;

namespace RestaurantMVCClient.Controllers
{
    public class OrderController : Controller
    {
        
        // GET: Dish
        public ActionResult Index()
        {
            return View();
        }

        // GET all diches
        public ActionResult GetAll()
        {
            return View();
        }

        // GET: Ingredient/Add
        public ActionResult Add()
        {
            return View();
        }
        public ActionResult AddDish(int id)
        {
            ViewBag.id = id;
            return View();

        }
        public ActionResult Edit(int id)
        {
            ViewBag.id = id;
            return View();
          
        }
        public ActionResult EditDish(int id)
        {
            ViewBag.id = id;
            return View();

        }
        public ActionResult GetDishes(int id)
        {
            ViewBag.id = id;
            return View();
        }

        public ActionResult Find()
        {
            return View();
        }
    }
}

RestaurantMVCClient/Views/Dish/Add.cshtml
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 40px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }

    a {
        color: darkcyan;
        margin-left: 10px;
        margin-right: 10px;
    }

    p {
        margin-top: 20px;
    }

    form {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 50%;
        height: auto;
    }

    input {
        border: 2px solid darkcyan;
        width: 100%;
        height: 60px;
        margin-bottom: 5%;
        border-radius: 2px;
    }
</style>
<h1>Add new dish</h1>

<form>
    <label>Name</label>
    <input type="text" id="DishName" placeholder="Write the name of dish" required />
    <input type="button" value="Add dish" onclick="add();"/>
</form>
<p><a href="/Dish/GetAll">Return to all dishes</a></p>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/restaurant/dish/add';
    function add() {
        var name = $('#DishName').val();
        var dish = { dishName: name };

        $.ajax({
        type: "POST",
            url: uri,
            data: JSON.stringify(dish),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: (function (data) {
                alert('Dish was added. ' + 'ID: ' + data.dishId + '; Name: ' + data.dishName);
                }),
            failure: function (err) {
                alert('Error: ' + err.Message);
                }
        });
        setTimeout(() => {  document.location.reload(true) }, 5000);

    }
</script>

RestaurantMVCClient/Views/Dish/AddIngredient.cshtml
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 40px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }

    a {
        color: darkcyan;
        margin-left: 10px;
        margin-right: 10px;
    }

    p {
        margin-top: 20px;
    }

    form {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 50%;
        height: auto;
    }

    input {
        border: 2px solid darkcyan;
        width: 100%;
        height: 60px;
        margin-bottom: 5%;
        border-radius: 2px;
    }
</style>
<h1>Add new ingredient for chosen dish</h1>

<form>
    <label>Ingredient Id</label>
    <input type="number" id="IngredientId" placeholder="Write id of ingredient" required />
    <input type="button" value="Add ingredient" onclick="add();"/>
</form>
<p id="return"></p>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var dishID = @ViewBag.id;
    var uri = 'https://localhost:5001/restaurant/dish/addingredient/' + dishID;
    $(document).ready(function(){
        $('<a>', { href: "/Dish/GetIngredients/" + dishID, text: "Return to all ingredients of this dish" }).appendTo($('#return'));
    });
    function add() {
        var ingrId = parseInt($('#IngredientId').val());
        $.post(uri + "/" + ingrId)
            .done(function (data) {
                alert('Ingredient was added. ');
            })
            .fail(function (err) {
                alert('Error: ' + err.Message);
            });
        
        setTimeout(() => {  document.location.reload(true) }, 5000);

    }
</script>

RestaurantMVCClient/Views/Dish/AddPrice.cshtml
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
     * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 40px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }

    a {
        color: darkcyan;
        margin-left: 10px;
        margin-right: 10px;
    }

    p {
        margin-top: 20px;
    }

    form {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 50%;
        height: auto;
    }

    input {
        border: 2px solid darkcyan;
        width: 100%;
        height: 60px;
        margin-bottom: 5%;
        border-radius: 2px;
    }
</style>
<h1>Add new price</h1>

<form>
    <label>Portion weight</label>
    <input type="number" id="Portion" placeholder="Write the weight of the portion" required />
    <label>Price per portion</label>
    <input type="number" id="PricePerPortion" placeholder="Write the price per portion" required />
    <input type="button" value="Add price" onclick="add();" />
</form>
<p><a href="/Dish/GetAll">Return to all dishes</a></p>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/restaurant/dish/addprice/';
    function add() {
        var portion = parseInt($('#Portion').val());
        var price = parseInt($('#PricePerPortion').val());
        var newPrice = { portion: portion, pricePerPortion: price };

        $.ajax({
        type: "POST",
            url: uri + @ViewBag.Id,
            data: JSON.stringify(newPrice),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: (function (data) {
                alert('Price was added. ');
                }),
            failure: function (err) {
                alert('Error: ' + err.Message);
                }
        });
        setTimeout(() => {  document.location.reload(true) }, 5000);

    }
</script>

RestaurantMVCClient/Views/Dish/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 40px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }

    a {
        color: darkcyan;
        margin-left: 10px;
    }

    p {
        margin-top: 30px;
    }

    form {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 50%;
        height: auto;
    }

    input {
        border: 2px solid darkcyan;
        width: 100%;
        height: 60px;
        margin-bottom: 10%;
        border-radius: 2px;
    }
</style>

<h1>Edit dish info</h1>

<form>
    <label>Name</label>
    <input type="text" id="DishName" placeholder="Write the name of dish" required />
    <input type="button" value="Edit dish" onclick="edit();"/>
</form>
<p><a href="/Dish/GetAll">Return to all dishes</a></p>
<script>
    var uri = 'https://localhost:5001/restaurant/dish/edit/';
    function edit() {
        var id = @ViewBag.Id;
        var name = $('#DishName').val();
        var dish = { dishName: name };

        $.ajax({
            type: "PUT",
            url: uri + id,
            data: JSON.stringify(dish),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: (function (data) {
                alert('Dish was updated. ' + 'ID: ' + data.dishId + '; Name: ' + data.dishName);
                }),
            failure: function (err) {
                alert('Error: ' + err.Message);
                }
        });
        setTimeout(() => {  document.location.reload(true) }, 5000);
    }
</script>

RestaurantMVCClient/Views/Dish/EditPrice.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
   * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 40px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }

    a {
        color: darkcyan;
        margin-left: 10px;
        margin-right: 10px;
    }

    p {
        margin-top: 20px;
    }

    form {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 50%;
        height: auto;
    }

    input {
        border: 2px solid darkcyan;
        width: 100%;
        height: 60px;
        margin-bottom: 5%;
        border-radius: 2px;
    }
</style>

<h1>Edit price info</h1>
<h2>Write new values in placehorders</h2>
<form method="post" action="">
    <label>Portion weight</label>
    <input type="number" id="Portion" placeholder="Write new value for portion weight" required />
    <label>Price per Portion</label>
    <input type="number" id="PricePerPortion" placeholder="Write new value for portion price" required />
    <input type="button" value="Edit price" onclick="edit();" />
</form>
<p><a href="/Dish/GetAll">Return to all dishes</a></p>
<script>
    var uri = 'https://localhost:5001/restaurant/dish/editprice/';
    function edit() {
        var priceID = @ViewBag.priceId;
        var dishID = @ViewBag.dishId;
        var weight = parseInt($('#Portion').val());
        var price = parseInt($('#PricePerPortion').val());
        var newPrice = { priceId: priceID, dishId: dishID, portion:  weight, pricePerPortion: price};

        $.ajax({
            type: "PUT",
            url: uri + priceID,
            data: JSON.stringify(newPrice),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: (function (data) {
                alert('Price was updated.');
                }),
            failure: function (err) {
                alert('Error: ' + err.Message);
                }
        });
        setTimeout(() => {  document.location.reload(true) }, 5000);
    }
</script>

RestaurantMVCClient/Views/Dish/Find.cshtml
@{
    ViewData["Title"] = "Find";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 30px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }
    
    p {
        margin-top: 20px;
    }

    form {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 50%;
        height: auto;
    }

    input {
        border: 2px solid darkcyan;
        width: 100%;
        height: 100px;
        margin-bottom: 5%;
        border-radius: 2px;
    }
    .div_table {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 70%;
        height: auto;
    }

    table {
        width: 100%;
        height: 100%;
        border-collapse: collapse;
    }

    tr {
        width: 100%;
        height: auto;
    }

    td {
        width: auto;
        height: auto;
        border: 2px solid black;
    }

    a, button {
        color: darkcyan;
        margin-left: 10px;
        margin-right: 10px;
        background: none;
    }

    .smallLink {
        color: cadetblue;
        font-size: 15px;
    }

    td p {
        margin-top: 5px;
        margin-bottom: 1px;
    }

</style>

<h1>Find dish info</h1>

<form>
    <label>Name</label>
    <input type="text" id="DishName" placeholder="Write the name of dish" required />
    <input type="button" value="Find dish" onclick="find();" />
</form>
<div class="div_table">
    <table id="dishes">
        <tr>
            <td>Dish Id</td>
            <td>Dish Name</td>
            <td>Portions</td>
            <td colspan="3">Commands</td>
        </tr>
    </table>
</div>
<p><a href="/Dish/Index">Return to dishes commands</a></p>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'https://localhost:5001/restaurant/dish/find/';
    function find() {
        var name = $('#DishName').val();
        $.getJSON(uri + name)
            .done(function (data) {
                var indexOfId = 0;
              $.each(data, function (key, item) {
                  var dishID = 0;
                  $('<tr>', { id: indexOfId }).appendTo($('#dishes'));
                  if (item.length == 0) {
                      dishID = find(key);
                      console.log(find(key));
                  }
                  else {
                      dishID = item[0].DishId;
                  }
                  $('<td>', { text: dishID }).appendTo($('#' + indexOfId));
                  $('<td>', { text: key }).appendTo($('#' + indexOfId));
                  $('<td>', { id: "portions" + indexOfId, text: ""}).appendTo($('#' + indexOfId));
                  if (item.length != 0) {
                      for (var price in item) {
                      $('<p>', { text: item[price].PriceId + ") " + item[price].Portion + "gr; " + item[price].PricePerPortion + "UAH;" }).append($('<br />')).appendTo($("#portions" + indexOfId));
                      var editPrice = $('<a>', { class: "smallLink", href: "/Dish/EditPrice?priceId=" + item[price].PriceId + '&dishId=' + item[price].DishId, text: "Edit price" });
                      var deletePrice = $('<a>', { class: "smallLink", href: "#", role: "button", onclick: "deletePrice(" + item[price].PriceId + ");", text: "Delete price" });
                      $('<p>').appendTo($("#portions" + indexOfId)).append(editPrice, deletePrice);
                      }
                  }
                 
                  var addPrice = $('<a>', { class: "smallLink", href: "/Dish/AddPrice/" + dishID, text: "Add price" }).append($('<br />'));
                  var ingredients = $('<a>', { href: "/Dish/GetIngredients/" + dishID, text: "Ingredients" }).append($('<br />'));
                  var editDish = $('<a>', { href: "/Dish/Edit/" + dishID, text: "Edit dish" }).append($('<br />'));
                  var deleteDish = $('<a>', { href: "#", role: "button", onclick: "deleteDish(" + dishID + ");", text: "Delete dish" }).append($('<br />'));
                  $('<td>').append(addPrice).appendTo($('#' + indexOfId));
                  $('<td>').append(ingredients, editDish, deleteDish).appendTo($('#' + indexOfId));
                  indexOfId += 1;
                })
            })
            .fail(function (err) {
                $('#dish').text('Error: ' + err.Message);
            });
    }
    function find(name) {
        var uri = 'https://localhost:5001/restaurant/dish/getbyname/';
        var id = 0;
        $.ajax({
        url: uri + name,
        async: false,
        success: function (data) {
            id = data.dishId
            }
        });
        return id;
    }
</script>

RestaurantMVCClient/Views/Dish/GetAll.cshtml
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@using System.Linq
<style>
    * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 35px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }

    .div_table {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 70%;
        height: auto;
    }

    table {
        width: 100%;
        height: 100%;
        border-collapse: collapse;
    }

    tr {
        width: 100%;
        height: auto;
    }

    td {
        width: auto;
        height: auto;
        border: 2px solid black;
    }

    a, button {
        color: darkcyan;
        margin-left: 10px;
        margin-right: 10px;
        background: none;
    }

    p {
        margin-top: 30px;
    }

    .smallLink {
        color: cadetblue;
        font-size: 15px;
    }

    td p {
        margin-top: 5px;
        margin-bottom: 1px;
    }

    p {
        margin-top: 20px;
    }
</style>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<h1>List of dishes</h1>
<div class="div_table">
    <table id="dishes">
        <tr>
            <td>Dish Id</td>
            <td>Dish Name</td>
            <td>Portions</td>
            <td colspan="3">Commands</td>
        </tr>
    </table>
</div>
<p><a href="/Dish/Add">Add new dish</a></p>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    function getall() {
        var uri = 'https://localhost:5001/restaurant/dish/getall';
      $.getJSON(uri)
          .done(function (data) {
              var indexOfId = 0;
              $.each(data, function (key, item) {
                  var dishID = 0;
                  $('<tr>', { id: indexOfId }).appendTo($('#dishes'));
                  if (item.length == 0) {
                      dishID = find(key);
                  }
                  else {
                      dishID = item[0].DishId;
                  }
                  $('<td>', { text: dishID }).appendTo($('#' + indexOfId));
                  $('<td>', { text: key }).appendTo($('#' + indexOfId));
                  $('<td>', { id: "portions" + indexOfId, text: ""}).appendTo($('#' + indexOfId));
                  if (item.length != 0) {
                      for (var price in item) {
                      $('<p>', { text: item[price].PriceId + ") " + item[price].Portion + "gr; " + item[price].PricePerPortion + "UAH;" }).append($('<br />')).appendTo($("#portions" + indexOfId));
                      var editPrice = $('<a>', { class: "smallLink", href: "/Dish/EditPrice?priceId=" + item[price].PriceId + '&dishId=' + item[price].DishId, text: "Edit price" });
                      var deletePrice = $('<a>', { class: "smallLink", href: "#", role: "button", onclick: "deletePrice(" + item[price].PriceId + ");", text: "Delete price" });
                      $('<p>').appendTo($("#portions" + indexOfId)).append(editPrice, deletePrice);
                      }
                  }
                 
                  var addPrice = $('<a>', { class: "smallLink", href: "/Dish/AddPrice/" + dishID, text: "Add price" }).append($('<br />'));
                  var ingredients = $('<a>', { href: "/Dish/GetIngredients/" + dishID, text: "Ingredients" }).append($('<br />'));
                  var editDish = $('<a>', { href: "/Dish/Edit/" + dishID, text: "Edit dish" }).append($('<br />'));
                  var deleteDish = $('<a>', { href: "#", role: "button", onclick: "deleteDish(" + dishID + ");", text: "Delete dish" }).append($('<br />'));
                  $('<td>').append(addPrice).appendTo($('#' + indexOfId));
                  $('<td>').append(ingredients, editDish, deleteDish).appendTo($('#' + indexOfId));
                  indexOfId += 1;
            });
          });
    }
    $(document).ready(getall);
    function deleteDish(id) {
        var uri = 'https://localhost:5001/restaurant/dish/delete/';
        $.ajax({
        type: "DELETE",
            url: uri + id,
            success: function () {
                alert('Dish was deleted');
                document.location.reload(true);
            },
            failure: function (err) {
                    alert('Error: ' + err.Message);
                }
        });
    }
    function deletePrice(id) {
        var uri = 'https://localhost:5001/restaurant/dish/deleteprice/';
        $.ajax({
        type: "DELETE",
            url: uri + id,
            success: function () {
                alert('Price was deleted');
                document.location.reload(true);
            },
            failure: function (err) {
                    alert('Error: ' + err.Message);
                }
        });
    }
    
    function find(name) {
        var uri = 'https://localhost:5001/restaurant/dish/getbyname/';
        var id = 0;
        $.ajax({
        url: uri + name,
        async: false,
        success: function (data) {
            id = data.dishId
            }
        });
        return id;
    }
</script>

RestaurantMVCClient/Views/Dish/GetIngredients.cshtml
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        text-align: center;
        font-size: 20px;
    }

    h1 {
        color: midnightblue;
        font-size: 35px;
        margin-top: 20px;
        text-align: center;
        margin-bottom: 20px;
    }

    .div_table {
        display: block;
        margin-right: auto;
        margin-left: auto;
        width: 70%;
        height: auto;
    }

    table {
        width: 100%;
        height: 100%;
        border-collapse: collapse;
    }

    tr {
        width: 100%;
        height: auto;
    }

    td {
        width: 50%;
        height: auto;
        border: 2px solid black;
    }

    a, button {
        color: darkcyan;
        margin-left: 10px;
        margin-right: 10px;
        background: none;
    }

    p {
        margin-top: 30px;
    }
</style>
<h1>List of ingredients for chosen dish</h1>
<div class="div_table">
    <table id="ingredients">
        <tr>
            <td>Ingredient Id</td>
            <td>Ingredient Name</td>
            <td colspan="1">Command</td>
        </tr>
    </table>
</div>
<p><a href="/Dish/GetAll">Return to all dishes</a></p>
<p id="add"></p>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var dishID = @ViewBag.id;
     $(document).ready(function(){
         $('<a>', { href: "/Dish/AddIngredient/" + dishID, text: "Add new ingredient" }).appendTo($('#add'));
    });
    function getall() {
        var uri = 'https://localhost:5001/restaurant/dish/getingredients/';
      $.getJSON(uri + dishID)
          .done(function (data) {
              $.each(data, function (key, item) {
                  $('<tr>', { id: item.ingredientName }).appendTo($('#ingredients'));
                  $('<td>', { text: item.ingredientId }).appendTo($('#' + item.ingredientName));
                  $('<td>', { text: item.ingredientName }).appendTo($('#' + item.ingredientName));
                  var deleteBut = $('<a>', { href:"#", role:"button", onclick: "deleteIngr("+item.ingredientId + ");", text: "Delete ingredient" });
                  $('<td>').append(deleteBut).appendTo($('#' + item.ingredientName));
              });
          });
    }
    $(document).ready(getall);
    function deleteIngr(id) {
        var uri = 'https://localhost:5001/restaurant/dish/deleteingredient/';
        $.ajax({
        type: "DELETE",
            url: uri + dishID + "/" + id,
            success: function () {
                alert('Ingredient was deleted');
                document.location.reload(true);
            },
            failure: function (err) {
                    alert('Error: ' + err.Message);
                }
        });
    }
</script>

RestaurantMVCClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="font-size: 15px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item" style="font-size: 15px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingredient" asp-action="Index">Ingredients</a>
                        </li>
                        <li class="nav-item" style="font-size: 15px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="Index">Dishes</a>
                        </li>
                        <li class="nav-item" style="font-size: 15px;">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PLMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>